### PR TITLE
200 bug cluster node initializes as healthy

### LINKED ISSUE #200: Split node healthcheck into 3: startup, readiness and liveness
Startup: returns OK - checks if the healthcheck program is running.
Liveness: returns OK if redis server returns any response, including PONG, BUSY, LOADING, etc.
Readiness: returns OK if:
- standalone: returns `PONG`
- replication: master -> `PONG`, replica -> `PONG` if it returns error during master synchronization
- cluster: `PONG` and cluster status is OK

### PR DESCRIPTION
**Pull request by MuhammadQadora**
fix #200 

## Summary by CodeRabbit

- **Chores**
  - Applied minor formatting improvements for consistency across scripts.
  - Added newline character to the end of a script for proper file formatting.

- **New Features**
  - Enhanced environment configuration with improved memory limit handling.
  - Revamped the health check system by introducing dedicated startup, readiness, and liveness checks across multiple configuration files.
  - Updated configuration settings across multiple deployment files to bolster monitoring and fault tolerance.

### CODE REVIEW

File: falkordb-cluster/cluster-entrypoint.sh [hunk 1]
```diff
@@ -73,6 +73,9 @@ DATE_NOW=$(date +"%Y%m%d%H%M%S")
 FALKORDB_LOG_FILE_PATH=$(if [[ $SAVE_LOGS_TO_FILE -eq 1 ]]; then echo $DATA_DIR/falkordb_$DATE_NOW.log; else echo ""; fi)
 NODE_CONF_FILE=$DATA_DIR/node.conf
 
+
+sleep 10
```
Comment (dudizimber) [inline falkordb-cluster/cluster-entrypoint.sh:77]: It'd be nice to get an explanation for that

File: falkordb-cluster/cluster-entrypoint.sh [hunk 2]
```diff
@@ -458,10 +461,6 @@ else
   echo "Cluster does not exist. Waiting for it to be created"
 fi
 
-# Run this before health check to prevent client connections until discrepancies are resolved.
-meet_unknown_nodes
-ensure_replica_connects_to_the_right_master_ip
-
```
Comment (dudizimber) [inline falkordb-cluster/cluster-entrypoint.sh:464]: why are those removed?

File: healthcheck_rs/src/main.rs [hunk 3]
```diff
@@ -26,7 +26,7 @@ fn main() {
 /// # Arguments
 /// 
 /// * `is_sentinel` - A boolean that indicates whether the health check server is for a Redis Sentinel instance.
-fn start_health_check_server(is_sentinel: bool) {
+fn start_probes_check_server(is_sentinel: bool) {
```
Comment (dudizimber) [inline healthcheck_rs/src/main.rs:29]: any reason for the name change?

File: healthcheck_rs/src/main.rs [hunk 4]
```diff
@@ -38,14 +38,26 @@ fn start_health_check_server(is_sentinel: bool) {
     let server = Server::new(addr, move |request| {
         router!(request,
             (GET) (/healthcheck) => {
```
Comment (dudizimber) [inline healthcheck_rs/src/main.rs:40]: maybe change the route to /liveness?

File: healthcheck_rs/src/main.rs [hunk 5]
```diff
@@ -74,7 +86,7 @@ fn start_health_check_server(is_sentinel: bool) {
 /// # Errors
 /// 
 /// The function returns a RedisError if there is an error connecting to the Redis server.
-fn health_check_handler(is_sentinel: bool) -> Result<bool, redis::RedisError> {
+fn probes_check_handler(is_sentinel: bool,readiness: bool, healthcheck: bool) -> Result<bool, redis::RedisError> {
```
Comment (dudizimber) [inline healthcheck_rs/src/main.rs:89]: i don't think aadding bool args are a clean solution. Maybe split into 3 functions and separate common components in util functions

Comment (dudizimber) [reply healthcheck_rs/src/main.rs:89]: that goes for all functions you added bools as params.
Let's make this easier to read

**Review by dudizimber — CHANGES_REQUESTED** [review]
see comments

File: healthcheck_rs/src/main.rs [hunk 6]
```diff
@@ -37,15 +37,27 @@ fn start_health_check_server(is_sentinel: bool) {
 
     let server = Server::new(addr, move |request| {
         router!(request,
-            (GET) (/healthcheck) => {
-                let health = health_check_handler(is_sentinel).unwrap_or_else(|_| false);
+            (GET) (/liveness) => {
```
Comment (dudizimber) [inline healthcheck_rs/src/main.rs:40]: Where's the startup route?

File: healthcheck_rs/src/main.rs [hunk 7]
```diff
@@ -54,6 +66,13 @@ fn start_health_check_server(is_sentinel: bool) {
     server.run();
 }
 
+fn liveness_check(is_sentinel: bool) -> Result<bool, redis::RedisError> {
+    check_handler_liveness(is_sentinel)
+}
+
+fn readiness_check(is_sentinel: bool) -> Result<bool, redis::RedisError> {
+    check_handler_readiness(is_sentinel)
+}
```
Comment (dudizimber) [inline healthcheck_rs/src/main.rs:75]: Why do we need these functions? Can't we just call the handler from inside the route?

File: healthcheck_rs/src/main.rs [hunk 8]
```diff
@@ -74,65 +93,125 @@ fn start_health_check_server(is_sentinel: bool) {
...
+    if is_sentinel {
+        return check_sentinel(&mut con);
+    }
+
+    let db_info: String = redis::cmd("INFO").query(&mut con)?;
+    let is_cluster = db_info.contains("cluster_enabled:1");
+
+    if is_cluster {
+        return check_cluster_node_liveness(db_info, &mut con);
+    }
```
Comment (dudizimber) [inline healthcheck_rs/src/main.rs:115]: This code is duplicated below. At least, you can abstract away the part to get a connection to the redis client

**Review by dudizimber — CHANGES_REQUESTED** [review]
see comments?

File: healthcheck_rs/src/main.rs [hunk 9]
```diff
@@ -74,65 +86,129 @@ fn start_health_check_server(is_sentinel: bool) {
...
+    Ok(con)
+}
+
+fn check_cluster_node_liveness(db_info: String, con: &mut redis::Connection) -> Result<bool, redis::RedisError> {
+    get_status_from_cluster_node_liveness(db_info, con)
+}
+
+fn check_cluster_node_readiness(db_info: String, con: &mut redis::Connection) -> Result<bool, redis::RedisError> {
+    get_status_from_cluster_node_readiness(db_info, con)
+}
```
Comment (dudizimber) [inline healthcheck_rs/src/main.rs:143]: These 2 functions seem unnecessary, as we can call the underlying function directly

**Review by dudizimber — CHANGES_REQUESTED** [review]
see comment

**Review by dudizimber — APPROVED** [review]
